definitions:
  controller.CreateResponse:
    properties:
      message:
        type: string
    type: object
  controller.ErrorResponse:
    properties:
      "200":
        type: string
      "400":
        type: string
      "500":
        type: string
    type: object
  repository.Category:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  repository.Order:
    properties:
      complete:
        type: boolean
      id:
        type: integer
      petId:
        type: integer
      quantity:
        type: integer
      shipDate:
        type: string
      status:
        type: string
    type: object
  repository.Pet:
    properties:
      category:
        $ref: '#/definitions/repository.Category'
      id:
        type: integer
      name:
        type: string
      photoUrls:
        items:
          type: string
        type: array
      status:
        type: string
      tags:
        items:
          $ref: '#/definitions/repository.Tag'
        type: array
    type: object
  repository.Tag:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Этот эндпоинт позволяет получить адрес по наименованию
  title: Swagger Petstore
  version: "1.0"
paths:
  /pet:
    post:
      consumes:
      - application/json
      description: This description addadder new pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Pet'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Add pet handler
      tags:
      - Controller
  /pet/:
    put:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Pet'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Update pet
      tags:
      - Controller
  /pet/{petId}:
    delete:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Pet'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Update pet
      tags:
      - Controller
    get:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Pet'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Update pet
      tags:
      - Controller
    post:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Pet'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Update pet
      tags:
      - Controller
  /pet/{petId}/uploadImage:
    post:
      consumes:
      - multipart/from-data
      description: This description upload image pet
      parameters:
      - description: file to addadder
        in: path
        name: petId
        required: true
        type: integer
      - description: Additional data to pass tp server
        in: formData
        name: additionalMetadata
        type: string
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Download image pet
      tags:
      - Controller
  /pet/findByStatus:
    get:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Status values that need to be considered for filter
        in: query
        name: status
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Find pet
      tags:
      - Controller
  /store/order:
    get:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Id order
      tags:
      - Store
    post:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Id order
      tags:
      - Store
  /store/order/{orderId}:
    delete:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Delete order
      tags:
      - Store
    get:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Id order
      tags:
      - Store
  /user/{username}:
    delete:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: List user order
      tags:
      - user
    get:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: List user order
      tags:
      - user
    put:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: List user order
      tags:
      - user
  /user/createWithArray:
    post:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: List user order
      tags:
      - user
  /user/createWithList:
    post:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: List user order
      tags:
      - user
  /user/login:
    get:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: List user order
      tags:
      - user
  /user/logout:
    get:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: List user order
      tags:
      - user
  /user/user:
    post:
      consumes:
      - application/json
      description: This description update pet
      parameters:
      - description: Pet addadder
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/repository.Order'
      produces:
      - application/json
      responses:
        "200":
          description: Create successful
          schema:
            $ref: '#/definitions/controller.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: List user order
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
